# cat docker-compose.yml
version: '3.3'
services:
### MySQL Container
  mysql:
    build:
      context: D:\Labs\mySQL\Dockerfile.yml
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"